- name: Install Restic
  ansible.builtin.apt:
    name: restic
    state: present
    update_cache: true

- name: Check if Restic repository exists
  ansible.builtin.command:
    cmd: restic cat config
  environment:
    RESTIC_REPOSITORY: "{{ vars[service_name].backups.restic.repository }}"
    RESTIC_PASSWORD: "{{ vars[service_name].backups.restic.password }}"
    AWS_ACCESS_KEY_ID: "{{ vars[service_name].backups.restic.access_key_id }}"
    AWS_SECRET_ACCESS_KEY: "{{ vars[service_name].backups.restic.secret_access_key }}"
  register: restic_check
  changed_when: false
  failed_when: false
  no_log: true

- name: Initialize Restic repository
  ansible.builtin.command:
    cmd: restic init
  environment:
    RESTIC_REPOSITORY: "{{ vars[service_name].backups.restic.repository }}"
    RESTIC_PASSWORD: "{{ vars[service_name].backups.restic.password }}"
    AWS_ACCESS_KEY_ID: "{{ vars[service_name].backups.restic.access_key_id }}"
    AWS_SECRET_ACCESS_KEY: "{{ vars[service_name].backups.restic.secret_access_key }}"
  when:
    - restic_check.rc != 0
    - "'does not exist' in restic_check.stderr"
  no_log: true

- name: Create Restic backup script
  template:
    src: restic/backup.sh.j2
    dest: "{{local_apps_path}}/{{service_name}}/restic-backup.sh"
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"
    mode: '0755'
  no_log: true

- name: Create Restic cron job
  ansible.builtin.cron:
    name: "Restic backup for {{ service_name }}"
    user: "{{ansible_user}}"
    job: "{{local_apps_path}}/{{service_name}}/restic-backup.sh >> /var/log/restic-{{ service_name }}.log 2>&1"
    minute: "{{ vars[service_name].backups.restic.cron_schedule.split(' ')[0] }}"
    hour: "{{ vars[service_name].backups.restic.cron_schedule.split(' ')[1] }}"
    day: "{{ vars[service_name].backups.restic.cron_schedule.split(' ')[2] }}"
    month: "{{ vars[service_name].backups.restic.cron_schedule.split(' ')[3] }}"
    weekday: "{{ vars[service_name].backups.restic.cron_schedule.split(' ')[4] }}"

